// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vsa_pkg.h for the primary calling header

#ifndef VERILATED_VSA_PKG___024ROOT_H_
#define VERILATED_VSA_PKG___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vsa_pkg__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vsa_pkg___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_gemm_top__DOT__clk;
        CData/*0:0*/ tb_gemm_top__DOT__rst_n;
        CData/*0:0*/ tb_gemm_top__DOT__start;
        CData/*0:0*/ tb_gemm_top__DOT__ld_a_en;
        CData/*2:0*/ tb_gemm_top__DOT__ld_a_row;
        CData/*7:0*/ tb_gemm_top__DOT__ld_a_data;
        CData/*0:0*/ tb_gemm_top__DOT__ld_b_en;
        CData/*2:0*/ tb_gemm_top__DOT__ld_b_col;
        CData/*7:0*/ tb_gemm_top__DOT__ld_b_data;
        CData/*0:0*/ tb_gemm_top__DOT__done_pulse_seen;
        CData/*1:0*/ tb_gemm_top__DOT__tile_size_kind;
        CData/*1:0*/ tb_gemm_top__DOT__k_kind;
        CData/*2:0*/ tb_gemm_top__DOT__coverage_events;
        CData/*0:0*/ tb_gemm_top__DOT__dut__DOT__array_en;
        CData/*0:0*/ tb_gemm_top__DOT__dut__DOT__clear_acc;
        CData/*0:0*/ tb_gemm_top__DOT__dut__DOT__feed_valid;
        CData/*0:0*/ tb_gemm_top__DOT__dut__DOT__capture;
        CData/*2:0*/ tb_gemm_top__DOT__dut__DOT__u_ctrl__DOT__state;
        CData/*2:0*/ tb_gemm_top__DOT__dut__DOT__u_ctrl__DOT__next_state;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_skew_a__DOT____Vlvbound_hd2c2c63b__0;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_skew_a__DOT____Vlvbound_h1b40498c__0;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_skew_a__DOT____Vlvbound_hb8fcdf94__0;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_skew_a__DOT____Vlvbound_h23489a8f__0;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_skew_b__DOT____Vlvbound_hd2c2c63b__0;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_skew_b__DOT____Vlvbound_h1b40498c__0;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_skew_b__DOT____Vlvbound_hb8fcdf94__0;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_skew_b__DOT____Vlvbound_h23489a8f__0;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__b_out;
    };
    struct {
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__b_out;
    };
    struct {
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__a_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__a_out;
        CData/*2:0*/ __Vdly__tb_gemm_top__DOT__coverage_events;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_gemm_top__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_gemm_top__DOT__rst_n__0;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ tb_gemm_top__DOT__K_in;
        SData/*15:0*/ tb_gemm_top__DOT__ld_a_k;
        SData/*15:0*/ tb_gemm_top__DOT__ld_b_k;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__k_idx;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_ctrl__DOT__k_cnt;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_ctrl__DOT__drain_cnt;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__0__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__0__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__0__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__0__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__0__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__0__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__0__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__0__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__1__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__1__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__1__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__1__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__1__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__1__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__1__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__1__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__2__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__2__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__2__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__2__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__2__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__2__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__2__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__2__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__3__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__3__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__DOT__product;
    };
    struct {
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__3__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__3__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__3__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__3__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__3__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__3__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__4__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__4__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__4__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__4__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__4__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__4__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__4__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__4__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__5__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__5__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__5__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__5__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__5__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__5__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__5__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__5__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__6__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__6__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__6__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__6__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__6__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__6__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__6__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__6__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__7__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__7__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__7__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__7__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__7__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__7__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__7__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__DOT__product;
        SData/*15:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT__g_row__BRA__7__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__DOT__product;
        IData/*31:0*/ tb_gemm_top__DOT__M;
        IData/*31:0*/ tb_gemm_top__DOT__N;
        IData/*31:0*/ tb_gemm_top__DOT__K;
        IData/*31:0*/ tb_gemm_top__DOT__checks;
        IData/*31:0*/ tb_gemm_top__DOT__errors;
        IData/*31:0*/ tb_gemm_top__DOT__tiles;
        IData/*31:0*/ tb_gemm_top__DOT__unnamedblk8__DOT__unnamedblk9__DOT__tn;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_ctrl__DOT__cyc;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc_out;
    };
    struct {
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ tb_gemm_top__DOT__dut__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__acc_out;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ tb_gemm_top__DOT__total_cycles;
        VlUnpacked<IData/*31:0*/, 64> tb_gemm_top__DOT__c_tile;
        VlUnpacked<CData/*7:0*/, 32768> tb_gemm_top__DOT__a_flat;
        VlUnpacked<CData/*7:0*/, 32768> tb_gemm_top__DOT__b_flat;
        VlUnpacked<IData/*31:0*/, 4096> tb_gemm_top__DOT__c_flat;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 512>, 8> tb_gemm_top__DOT__dut__DOT__a_mem;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 8>, 512> tb_gemm_top__DOT__dut__DOT__b_mem;
        VlUnpacked<CData/*7:0*/, 8> tb_gemm_top__DOT__dut__DOT__a_unskewed;
        VlUnpacked<CData/*7:0*/, 8> tb_gemm_top__DOT__dut__DOT__b_unskewed;
        VlUnpacked<CData/*7:0*/, 8> tb_gemm_top__DOT__dut__DOT__a_skewed;
        VlUnpacked<CData/*7:0*/, 8> tb_gemm_top__DOT__dut__DOT__b_skewed;
        VlUnpacked<IData/*31:0*/, 64> tb_gemm_top__DOT__dut__DOT__c_live;
        VlUnpacked<CData/*7:0*/, 1> tb_gemm_top__DOT__dut__DOT__u_skew_a__DOT__g_lane__BRA__1__KET____DOT__g_delay__DOT__pipe;
        VlUnpacked<CData/*7:0*/, 2> tb_gemm_top__DOT__dut__DOT__u_skew_a__DOT__g_lane__BRA__2__KET____DOT__g_delay__DOT__pipe;
        VlUnpacked<CData/*7:0*/, 3> tb_gemm_top__DOT__dut__DOT__u_skew_a__DOT__g_lane__BRA__3__KET____DOT__g_delay__DOT__pipe;
        VlUnpacked<CData/*7:0*/, 4> tb_gemm_top__DOT__dut__DOT__u_skew_a__DOT__g_lane__BRA__4__KET____DOT__g_delay__DOT__pipe;
        VlUnpacked<CData/*7:0*/, 5> tb_gemm_top__DOT__dut__DOT__u_skew_a__DOT__g_lane__BRA__5__KET____DOT__g_delay__DOT__pipe;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 6> tb_gemm_top__DOT__dut__DOT__u_skew_a__DOT__g_lane__BRA__6__KET____DOT__g_delay__DOT__pipe;
        VlUnpacked<CData/*7:0*/, 7> tb_gemm_top__DOT__dut__DOT__u_skew_a__DOT__g_lane__BRA__7__KET____DOT__g_delay__DOT__pipe;
        VlUnpacked<CData/*7:0*/, 1> tb_gemm_top__DOT__dut__DOT__u_skew_b__DOT__g_lane__BRA__1__KET____DOT__g_delay__DOT__pipe;
        VlUnpacked<CData/*7:0*/, 2> tb_gemm_top__DOT__dut__DOT__u_skew_b__DOT__g_lane__BRA__2__KET____DOT__g_delay__DOT__pipe;
        VlUnpacked<CData/*7:0*/, 3> tb_gemm_top__DOT__dut__DOT__u_skew_b__DOT__g_lane__BRA__3__KET____DOT__g_delay__DOT__pipe;
        VlUnpacked<CData/*7:0*/, 4> tb_gemm_top__DOT__dut__DOT__u_skew_b__DOT__g_lane__BRA__4__KET____DOT__g_delay__DOT__pipe;
        VlUnpacked<CData/*7:0*/, 5> tb_gemm_top__DOT__dut__DOT__u_skew_b__DOT__g_lane__BRA__5__KET____DOT__g_delay__DOT__pipe;
        VlUnpacked<CData/*7:0*/, 6> tb_gemm_top__DOT__dut__DOT__u_skew_b__DOT__g_lane__BRA__6__KET____DOT__g_delay__DOT__pipe;
        VlUnpacked<CData/*7:0*/, 7> tb_gemm_top__DOT__dut__DOT__u_skew_b__DOT__g_lane__BRA__7__KET____DOT__g_delay__DOT__pipe;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 9>, 8> tb_gemm_top__DOT__dut__DOT__u_array__DOT__a_h;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 8>, 9> tb_gemm_top__DOT__dut__DOT__u_array__DOT__b_v;
    };
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_h36e11883__0;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<3> __VactTriggered;
    VlTriggerVec<3> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vsa_pkg__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vsa_pkg___024root(Vsa_pkg__Syms* symsp, const char* v__name);
    ~Vsa_pkg___024root();
    VL_UNCOPYABLE(Vsa_pkg___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
